miraizura/urls.py
from django.urls import path

from . import views



app_name = 'miraizura'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('diary_list/', views.DiaryListView.as_view(), name="diary_list"),
    path('diary_detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary_create/', views.DiaryCreateView.as_view(), name="diary_create"),
    path('diary_update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary_delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
]

zuramaru/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('miraizura.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL,
                      document_root=settings_dev.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """Extended User Model"""

    class Meta:
        verbose_name_plural = 'CustomUser'

miraizura/models.py
from accounts.models import CustomUser
from django.db import models

class Diary(models.Model):

    user = models.ForeignKey(CustomUser, verbose_name='user', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='title', max_length=40)
    content = models.TextField(verbose_name='content', blank=True, null=True)
    photo1 = models.ImageField(verbose_name='photo1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='photo2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='photo3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='created date', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='updated date', auto_now=True)

    class Meta:
        verbose_name_plural = 'Diary'

        def __str__(self):
            return self.title

miraizura/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import Diary

class InquiryForm(forms.Form):
    name = forms.CharField(label='Name', max_length=30)
    email = forms.EmailField(label='Email address')
    title = forms.CharField(label='Title', max_length=30)
    message = forms.CharField(label='Message', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col9'
        self.fields['name'].widget.attrs['placeholder'] = 'Enter your name'

        self.fields['email'].widget.attrs['class'] = 'form-control col11'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email address'

        self.fields['title'].widget.attrs['class'] = 'form-control col11'
        self.fields['title'].widget.attrs['placeholder'] = 'Enter the title'

        self.fields['message'].widget.attrs['class'] = 'form-control col12'
        self.fields['message'].widget.attrs['placeholder'] = 'Enter a message'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = "Inquiry {}".format(title)
        message = "Sender's name: {0}\nEmail address: {1}\nMessage:\n{2}".format(name, email, message)
        from_email = 'admin@example.com'
        to_list = ['test@example.com']
        cc_list = [email]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render

# Create your views here.

miraizura/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .forms import InquiryForm, DiaryCreateForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Diary

import logging

Logger = logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('miraizura:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'The message has been sent successfully.')
        Logger.info('Inquiry send by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 5

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('miraizura:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, 'The diary has been created successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'The diary has been failed to create.')
        return super().form_invalid(form)

class DiaryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('miraizura:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'The diary has been updated successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.success(self.request, 'The diary has failed to be update.')
        return super().form_invalid(form)

class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('miraizura:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'The diary has been deleted successfully.')
        return super().delete(request, *args, **kwargs)

miraizura/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <Link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <Link href="https://fonts.googleapis.com/css?family=Catamaran: 100,200,300,400,500,600,700,800,900,900i"
          rel="stylesheet">
    <Link href="https://fonts.googleapis.com/css?family=Lato: 100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
 <div id="wrapper">
     <!-- Navigation -->
     <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
         <div class="container">
             <a class="navbar-brand" href="{% url 'miraizura:index' %}">TOP<a/>
             <button class="navbar-toggler" type="button" data-toggle="collapse"
             data-target="#navbarResponsive" aria-label="Toggle navigation">
                 <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarResponsive">
                 <ul class="navbar-nav mr-auto">
                     <li class="nav-item {% block active_inquiry %}{% endblock%}">
                         <a class="nav-link" href="{% url 'miraizura:inquiry' %}">INQUIRY</a>
                     </li>
                     {% if user.is_authenticated %}
                     <li class="nav-item {% block active_diary_list %}{% endblock %}">
                         <a class="nav-link" href="{% url 'miraizura:diary_list' %}">DIARY LIST</a>
                     {% endif %}
                 </ul>
                 <ul class="navbar-nav ml-auto">
                     {% if user.is_authenticated %}
                     <li class="nav-item">
                         <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                     </li>
                     {% else %}
                     <li class="nav-item {% block active_signup %}{% endblock %}">
                         <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                     </li>
                     <li class="nav-item {% block active_login %}{% endblock %}">
                         <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                     {% endif %}
                     </li>
                 </ul>
             </div>
         </div>
     </nav>

     {% block header%}{% endblock %}

     {% if messages %}
     <div class="container">
         <div class="row">
             <div class="my-div-style w-100">
                 <ul class="messages" style="list-style: none;">
                     {% for message in messages%}
                     <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                         {{ message }}
                     </li>
                     {% endfor %}
                 </ul>
             </div>
         </div>
     {% endif %}

     {% block contents%}{% endblock %}

     <!-- Footer -->
     <footer class="py-5 bg-black">
         <div class="container">
             <p class="m-0 text-center text-white small">Copyright &copy; Zuramaru 2020</p>
         </div>
         <!-- /.container -->
     </footer>

     <!-- Bootstrap core JavaScript -->
     <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
     <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 </div>
</body>

</html>

miraizura/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}DIARY CREATE | Zuramaru{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

miraizura/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}DIARY DELETE | Zuramaru{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>Are you surely ready to delete?</p>
                <button class="btn btn-primary mt-5" type="submit">Delete</button>
                <a class="btn btn-secondary mt-5 mt-2" href="{% url 'miraizura:diary_detail' object.pk %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

miraizura/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}DIARY DETAIL | Zuramaru{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>Title</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Article</strong>
            </div>
            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Photo</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                   <img src="{{ object.photo1.url }}" width="200" height="200"/>
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                   <img src="{{ object.photo2.url }}" width="200" height="200"/>
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                   <img src="{{ object.photo3.url }}" width="200" height="200"/>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-3">
                <strong>Created date</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>Updated date</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>

        <a class="btn btn-success mt-5 mb-3" href="{% url 'miraizura:diary_update' object.pk %}">Update</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'miraizura:diary_delete' object.pk %}">Delete</a>
    </div>
</div>
{% endblock %}

miraizura/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}DIARY LIST | Zuramaru{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<Link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'miraizura:diary_create' %}">New</a>
                </div>
                {% for miraizura in diary_list %}
                <div class="post-preview">
                    <a href="{% url 'miraizura:diary_detail' miraizura.pk %}">
                        <h2 class="post-title">
                            {{ miraizura.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ miraizura.content|truncatechars:20 }}
                        </h3>
                    </a>
                    <p class="post-meta">{{ miraizura.created_at }}</p>
                </div>
                <hr>
                {% empty %}
                <p>There is no displayable diary.</p>
                {% endfor %}

                <!-- Pagination processing -->

                {% if is_paginated %}
                <ul class="pagination">
                    <!-- the link to the previous page -->
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                     <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                         <span aria-hidden="true">&laquo;</span>
                     </a>
                    </li>
                    {% endif %}

                    <!-- the number of the displaying page -->
                    {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- The link to the next page -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                     <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                         <span aria-hidden="true">&raquo;</span>
                     </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

miraizura/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}DIARY UPDATE | Zuramaru{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">Update</button>
                <a class="btn btn-secondary ml-2" href="{% url 'miraizura:diary_detail' object.pk %}">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

miraizura/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}TOP | Zuramaru{% endblock %}

{% block header%}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
            <h1 class="masthead-heading mb-0">Zuramaru</h1>
            <h2 class="masthead-subheading mb-0">Your own "Diary saving service"</h2>
            <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<selection>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/Graceon_01.jpeg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Web Diary</h2>
                    <p>A diary which enables you to create/update/delete on the Web site</p>
                </div>
            </div>
        </div>
    </div>
</selection>

<selection>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/Graceon_02.jpeg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">Save your diary</h2>
                    <p>Save your diary on the Web page</p>
                </div>
            </div>
        </div>
    </div>
</selection>

<selection>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="{% static 'img/Graceon_03.jpeg' %}" alt="">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Membership System</h2>
                    <p>A web diary service for members only</p>
                </div>
            </div>
        </div>
    </div>
</selection>
{% endblock %}

miraizura/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}INQUIRY | Zuramaru{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors}}

                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">
                        {{ field }}
                        {{ field.error }}
                    </div>
                </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}